// Icon mapping utility for Lucide Vue icons
import {
  Flag,
  CheckCircle,
  Users,
  Plus,
  Edit,
  Trash2,
  Settings,
  Search,
  X,
  ChevronLeft,
  ChevronRight,
  ChevronDown,
  ChevronUp,
  ArrowUp,
  ArrowDown,
  Minus,
  Filter,
  Calendar,
  Clock,
  AlertCircle,
  Info,
  CheckCircle2,
  XCircle,
  AlertTriangle,
  BarChart3,
  PieChart,
  TrendingUp,
  TrendingDown,
  Eye,
  EyeOff,
  Lock,
  Mail,
  User,
  LogOut,
  Menu,
  MoreVertical
} from 'lucide-vue-next'

// Export icon components
export {
  Flag,
  CheckCircle,
  Users,
  Plus,
  Edit,
  Trash2,
  Settings,
  Search,
  X,
  ChevronLeft,
  ChevronRight,
  ChevronDown,
  ChevronUp,
  ArrowUp,
  ArrowDown,
  Minus,
  Filter,
  Calendar,
  Clock,
  AlertCircle,
  Info,
  CheckCircle2,
  XCircle,
  AlertTriangle,
  BarChart3,
  PieChart,
  TrendingUp,
  TrendingDown,
  Eye,
  EyeOff,
  Lock,
  Mail,
  User,
  LogOut,
  Menu,
  MoreVertical
}

// Icon name to component mapping
export const iconMap = {
  'flag': Flag,
  'check-circle': CheckCircle,
  'users': Users,
  'plus': Plus,
  'edit': Edit,
  'trash': Trash2,
  'settings': Settings,
  'search': Search,
  'x': X,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'chevron-down': ChevronDown,
  'chevron-up': ChevronUp,
  'arrow-up': ArrowUp,
  'arrow-down': ArrowDown,
  'minus': Minus,
  'filter': Filter,
  'calendar': Calendar,
  'clock': Clock,
  'alert-circle': AlertCircle,
  'info': Info,
  'check-circle-2': CheckCircle2,
  'x-circle': XCircle,
  'alert-triangle': AlertTriangle,
  'bar-chart': BarChart3,
  'pie-chart': PieChart,
  'trending-up': TrendingUp,
  'trending-down': TrendingDown,
  'eye': Eye,
  'eye-off': EyeOff,
  'lock': Lock,
  'mail': Mail,
  'user': User,
  'logout': LogOut,
  'menu': Menu,
  'more-vertical': MoreVertical
}

// Helper function to get icon component by name
export function getIcon(name) {
  return iconMap[name] || null
}

export default {
  ...iconMap,
  getIcon
}
